# Generated by Django 4.1.3 on 2022-12-01 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sholat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='jadwal',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Jadwal'},
        ),
        migrations.AlterModelOptions(
            name='kota',
            options={'verbose_name_plural': 'Kota'},
        ),
        migrations.CreateModel(
            name='Imam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('hari', models.CharField(max_length=100)),
                ('jam', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sholat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.sholat')),
            ],
        ),
    ]
