# Generated by Django 4.1.3 on 2022-12-01 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_sholat_alter_jadwal_options_alter_kota_options_imam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imam',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Imam'},
        ),
        migrations.AlterModelOptions(
            name='sholat',
            options={'verbose_name_plural': 'Sholat'},
        ),
        migrations.RenameField(
            model_name='imam',
            old_name='sholat',
            new_name='shalat',
        ),
    ]
