# Generated by Django 4.1.3 on 2022-12-01 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_imam_options_alter_sholat_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imam',
            old_name='shalat',
            new_name='sholats',
        ),
    ]
