# Generated by Django 4.1.3 on 2022-12-01 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_shalat_imam_sholats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Imam',
        ),
        migrations.DeleteModel(
            name='Sholat',
        ),
    ]
