# Generated by Django 4.1.3 on 2022-12-01 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_delete_imam_delete_sholat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sholat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Sholat',
            },
        ),
        migrations.CreateModel(
            name='Imam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('hari', models.CharField(max_length=100)),
                ('jam', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('sholata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.sholat')),
            ],
            options={
                'verbose_name_plural': 'Sholat',
                'ordering': ['-date'],
            },
        ),
    ]
