# Generated by Django 4.1.3 on 2022-12-13 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_sholat_imam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imam',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Imam'},
        ),
    ]
