# Generated by Django 4.1.3 on 2022-12-19 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_imam_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jadwal',
            name='maghrib',
        ),
        migrations.AddField(
            model_name='jadwal',
            name='magrib',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jadwal',
            name='tanggal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jadwal',
            name='ashr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jadwal',
            name='dhuha',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jadwal',
            name='dzuhur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jadwal',
            name='isya',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jadwal',
            name='shubuh',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jadwal',
            name='terbit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
