# Generated by Django 4.1.3 on 2022-12-19 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_jadwal_options_remove_jadwal_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kota',
            new_name='Tanggal',
        ),
        migrations.AlterModelOptions(
            name='tanggal',
            options={'verbose_name_plural': 'Tanggal'},
        ),
    ]
